name: firmware build
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Check code format
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check clang-format
        uses: jidicula/clang-format-action@v4.9.0
        with:
          check-path: "code"
          exclude-regex: '\/build\/'

  build-blinky:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    name: Build blinky
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build blinky
        uses: ./.github/actions/build
        with:
          sample: blinky
          soc: nrf52840
          revision: 2.0.0
          output-bin: blinky_nrf52840_2.0.0.hex

  build-input:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    name: Build input
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build input
        uses: ./.github/actions/build
        with:
          sample: input
          soc: nrf52840
          revision: 2.0.0
          output-bin: input_nrf52840_2.0.0.hex

  build-soil-read-loop:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    name: Build soil_read_loop
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build soil_read_loop
        uses: ./.github/actions/build
        with:
          sample: soil-read-loop
          soc: nrf52840
          revision: 2.0.0
          output-bin: soil_read_loop_nrf52840_2.0.0.hex

  build-ble:
    strategy:
      matrix:
        soc: [nrf52840, nrf52833]
        revision: [1.1.0, 1.2.0, 2.0.0]
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    name: Build ble ${{ matrix.soc }}@${{ matrix.revision }}
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          sample: ble
          soc: ${{ matrix.soc }}
          revision: ${{ matrix.revision }}
          cmake-extra: -DCONFIG_PRST_BLE_ENCODING_BTHOME_V2=y -DCONFIG_PRSTLIB_LOG_LEVEL_DBG=n
          output-bin: ble_${{ matrix.soc }}_${{ matrix.revision }}.hex

  build-zigbee:
    strategy:
      matrix:
        soc: [nrf52840, nrf52833]
        revision: [1.2.0, 2.0.0]
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    name: Build zigbee ${{ matrix.soc }}@${{ matrix.revision }}
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          sample: zigbee
          soc: ${{ matrix.soc }}
          revision: ${{ matrix.revision }}
          cmake-extra: -DCONFIG_PRSTLIB_LOG_LEVEL_DBG=n
          output-bin: zigbee_${{ matrix.soc }}_${{ matrix.revision }}.hex

  # Create a draft release if the build was triggered by a v* tag push.
  maybe-release:
    needs:
      [build-blinky, build-input, build-soil-read-loop, build-ble, build-zigbee]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true
      - name: Generate SHA256 checksums
        working-directory: artifacts
        run: sha256sum *.hex > SHA256SUMS.txt

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          files: |
            artifacts/*
            artifacts/SHA256SUMS.txt
